server:
  port: 30000
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
      #defaultZone: http://localhost:20001/eureka/,http://localhost:20002/eureka/

  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5s钟向服务器发送一条服务续约的指令
    lease-expiration-duration-in-seconds: 60  #如果60s内，依然没有收到续约请求，则判定服务过期
