spring:
  application:
    name: eureka

server:
  port: 20001


#Eureka配置
eureka:
  instance:
    hostname: peer1 #Eureka服务端的实例名称
  client:
    register-with-eureka: true   #表示是否向注册中心注册自己
    fetch-registry: true   #为false表示自己是注册中心
    service-url:    #监控页面
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群（关联）
      defaultZone: http://peer2:20002/eureka/