server:
  port: 65100

spring:
  application:
    name: auth-service-api
  redis:
    port: 6379
    host: localhost
    database: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/

logging:
  file:
    ${spring.application.name}.log
management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
