spring:
  application:
    name: zipkin-server
  main:
    allow-bean-definition-overriding: true

server:
  port: 2439



management:
  metrics:
    web:
      server:
        auto-time-requests: false


